import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'de' | 'es' | 'fr' | 'zh' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.digitalTwin': 'Operations',
    'nav.valueChain': 'Value Chain',
    'nav.valueChainSim': 'Value Chain Simulation',
    'nav.manufacturing': 'Manufacturing',
    'nav.manufacturingSim': 'Manufacturing Simulation',
    'nav.logistics': 'Logistics',
    'nav.product': 'Product Quality',
    'nav.sustainability': 'Sustainability Assessment',
    'nav.decisionSupport': 'Decision Support',
    'nav.moDss': 'Multi-Objective Optimization',
    'nav.knowledgeGraph': 'Decision Knowledge Graph',
    'nav.alertCenter': 'Alert Center',
    'nav.glossary': 'Glossary',
    'nav.helpTraining': 'Help & Training',
    'header.search': 'Search...',
    'header.lastHours': 'Last 24 Hours',
    'header.last7Days': 'Last 7 Days',
    'header.last30Days': 'Last 30 Days',
    'header.last90Days': 'Last 90 Days',
    'header.refresh': 'Refresh data',
    'header.notifications': 'Notifications',
    'header.language': 'Language',
    'status.online': 'System Online',
    'status.warning': 'System Warning',
    'status.critical': 'System Critical',
    'dashboard.title': 'Operations Dashboard',
    'dashboard.subtitle': 'Real-time overview of value chain performance',
    'dashboard.kpi.oee': 'Overall Equipment Effectiveness',
    'dashboard.kpi.throughput': 'Daily Throughput',
    'dashboard.kpi.defectRate': 'Defect Rate',
    'dashboard.kpi.energyEfficiency': 'Energy Efficiency',
    'dashboard.kpi.sustainability': 'Sustainability Score',
    'dashboard.kpi.supplyChainRisk': 'Supply Chain Risk Index',
    'dashboard.alerts': 'Recent Alerts',
    'dashboard.viewAll': 'View All',
    'alerts.title': 'Alert Center',
    'alerts.subtitle': 'Monitor and manage system alerts',
    'alerts.filter.all': 'All',
    'alerts.filter.critical': 'Critical',
    'alerts.filter.warning': 'Warning',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Acknowledge',
    'alerts.acknowledged': 'Acknowledged',
    'alerts.details': 'Details',
    'alerts.sampleTitle': 'Sample alerts.',
    'alerts.sampleBody': 'These entries are measured from the raw {company} data — the source table, column and measured figure are printed under each alert. They illustrate the alert workflow; there is no live connection.',
    'alerts.sampleBadge': 'Sample',
    'common.apply': 'Apply',
    'common.dismiss': 'Dismiss',
    'common.seeDetails': 'See Details',
    'common.export': 'Export',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred. Please try again.',
    'common.noData': 'No data available',
    'onboarding.welcome': 'Welcome to SMAP',
    'onboarding.step1.title': 'Dashboard Overview',
    'onboarding.step1.desc': 'Monitor your key performance indicators and system health at a glance.',
    'onboarding.step2.title': 'Cognitive Digital Twins',
    'onboarding.step2.desc': 'Explore real-time digital representations and run what-if simulations.',
    'onboarding.step3.title': 'Decision Support & Sustainability',
    'onboarding.step3.desc': 'Get AI-powered optimization recommendations and sustainability assessments.',
    'onboarding.step4.title': 'Alert Center',
    'onboarding.step4.desc': 'Stay informed about critical events and system notifications.',
    'onboarding.next': 'Next',
    'onboarding.prev': 'Previous',
    'onboarding.finish': 'Get Started',
    'onboarding.skip': 'Skip Tour',
    'onboarding.dontShowAgain': "Don't show this again",
    'adminTour.welcome': 'Welcome to SMAP Admin',
    'adminTour.step1.title': 'Users & Roles',
    'adminTour.step1.desc': 'Create, edit and remove accounts, and assign the manager, engineer or operator role. You only see and manage users of your own use case.',
    'adminTour.step2.title': 'Pages & Cards',
    'adminTour.step2.desc': 'Decide which pages and which cards each role can see. A change takes effect immediately in that role’s view.',
    'adminTour.step3.title': 'Scope & storage',
    'adminTour.step3.desc': 'This is a demo configuration and is stored in this browser only. It covers your own use case; the other use case is configured from its own admin account.',
  },
  de: {
    'nav.dashboard': 'Dashboard',
    'nav.digitalTwin': 'Kognitive Digitale Zwillinge',
    'nav.valueChain': 'Wertschöpfungskette',
    'nav.valueChainSim': 'Wertschöpfungsketten-Simulation',
    'nav.manufacturing': 'Fertigung',
    'nav.manufacturingSim': 'Fertigungs-Simulation',
    'nav.logistics': 'Logistik',
    'nav.product': 'Produktqualität',
    'nav.sustainability': 'Nachhaltigkeitsbewertung',
    'nav.decisionSupport': 'Entscheidungsunterstützung',
    'nav.moDss': 'Mehrziel-Optimierung',
    'nav.knowledgeGraph': 'Entscheidungswissensgraph',
    'nav.alertCenter': 'Warnzentrale',
    'nav.glossary': 'Glossar',
    'nav.helpTraining': 'Hilfe & Schulung',
    'header.search': 'Suchen...',
    'header.lastHours': 'Letzte 24 Stunden',
    'header.last7Days': 'Letzte 7 Tage',
    'header.last30Days': 'Letzte 30 Tage',
    'header.last90Days': 'Letzte 90 Tage',
    'header.refresh': 'Daten aktualisieren',
    'header.notifications': 'Benachrichtigungen',
    'header.language': 'Sprache',
    'status.online': 'System Online',
    'status.warning': 'Systemwarnung',
    'status.critical': 'System Kritisch',
    'dashboard.title': 'Betriebs-Dashboard',
    'dashboard.subtitle': 'Echtzeit-Übersicht der Wertschöpfungskettenleistung',
    'dashboard.kpi.oee': 'Gesamtanlageneffektivität',
    'dashboard.kpi.throughput': 'Täglicher Durchsatz',
    'dashboard.kpi.defectRate': 'Fehlerquote',
    'dashboard.kpi.energyEfficiency': 'Energieeffizienz',
    'dashboard.kpi.sustainability': 'Nachhaltigkeitsbewertung',
    'dashboard.kpi.supplyChainRisk': 'Lieferkettenrisikoindex',
    'dashboard.alerts': 'Aktuelle Warnungen',
    'dashboard.viewAll': 'Alle anzeigen',
    'alerts.title': 'Warnzentrale',
    'alerts.subtitle': 'Systemwarnungen überwachen und verwalten',
    'alerts.filter.all': 'Alle',
    'alerts.filter.critical': 'Kritisch',
    'alerts.filter.warning': 'Warnung',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Bestätigen',
    'alerts.acknowledged': 'Bestätigt',
    'alerts.details': 'Details',
    'alerts.sampleTitle': 'Beispielwarnungen.',
    'alerts.sampleBody': 'Diese Einträge wurden aus den Rohdaten von {company} gemessen — Quelltabelle, Spalte und gemessener Wert stehen unter jeder Warnung. Sie veranschaulichen den Warnablauf; es besteht keine Live-Verbindung.',
    'alerts.sampleBadge': 'Beispiel',
    'common.apply': 'Anwenden',
    'common.dismiss': 'Verwerfen',
    'common.seeDetails': 'Details anzeigen',
    'common.export': 'Exportieren',
    'common.loading': 'Laden...',
    'common.error': 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    'common.noData': 'Keine Daten verfügbar',
    'onboarding.welcome': 'Willkommen bei SMAP',
    'onboarding.step1.title': 'Dashboard-Übersicht',
    'onboarding.step1.desc': 'Überwachen Sie Ihre wichtigsten Leistungskennzahlen und den Systemzustand auf einen Blick.',
    'onboarding.step2.title': 'Kognitive Digitale Zwillinge',
    'onboarding.step2.desc': 'Erkunden Sie Echtzeit-Darstellungen und führen Sie Was-wäre-wenn-Simulationen durch.',
    'onboarding.step3.title': 'Entscheidungsunterstützung & Nachhaltigkeit',
    'onboarding.step3.desc': 'Erhalten Sie KI-gestützte Optimierungsempfehlungen und Nachhaltigkeitsbewertungen.',
    'onboarding.step4.title': 'Warnzentrale',
    'onboarding.step4.desc': 'Bleiben Sie über kritische Ereignisse und Systembenachrichtigungen informiert.',
    'onboarding.next': 'Weiter',
    'onboarding.prev': 'Zurück',
    'onboarding.finish': 'Loslegen',
    'onboarding.skip': 'Tour überspringen',
    'onboarding.dontShowAgain': 'Nicht mehr anzeigen',
    'adminTour.welcome': 'Willkommen bei SMAP Admin',
    'adminTour.step1.title': 'Benutzer & Rollen',
    'adminTour.step1.desc': 'Konten anlegen, bearbeiten und entfernen sowie die Rolle Manager, Ingenieur oder Bediener zuweisen. Sie sehen und verwalten nur Benutzer Ihres eigenen Anwendungsfalls.',
    'adminTour.step2.title': 'Seiten & Karten',
    'adminTour.step2.desc': 'Legen Sie fest, welche Seiten und Karten jede Rolle sehen darf. Eine Änderung wirkt sofort in der Ansicht dieser Rolle.',
    'adminTour.step3.title': 'Geltungsbereich & Speicherung',
    'adminTour.step3.desc': 'Dies ist eine Demo-Konfiguration und wird nur in diesem Browser gespeichert. Sie gilt für Ihren eigenen Anwendungsfall; der andere Anwendungsfall wird über sein eigenes Administratorkonto konfiguriert.',
  },
  es: {
    'nav.dashboard': 'Panel de Control',
    'nav.digitalTwin': 'Gemelos Digitales Cognitivos',
    'nav.valueChain': 'Cadena de Valor',
    'nav.valueChainSim': 'Simulación de Cadena de Valor',
    'nav.manufacturing': 'Fabricación',
    'nav.manufacturingSim': 'Simulación de Fabricación',
    'nav.logistics': 'Logística',
    'nav.product': 'Calidad del Producto',
    'nav.sustainability': 'Evaluación de Sostenibilidad',
    'nav.decisionSupport': 'Soporte de Decisiones',
    'nav.moDss': 'Optimización Multiobjetivo',
    'nav.knowledgeGraph': 'Grafo de Conocimiento de Decisiones',
    'nav.alertCenter': 'Centro de Alertas',
    'nav.glossary': 'Glosario',
    'nav.helpTraining': 'Ayuda y Formación',
    'header.search': 'Buscar...',
    'header.lastHours': 'Últimas 24 Horas',
    'header.last7Days': 'Últimos 7 Días',
    'header.last30Days': 'Últimos 30 Días',
    'header.last90Days': 'Últimos 90 Días',
    'header.refresh': 'Actualizar datos',
    'header.notifications': 'Notificaciones',
    'header.language': 'Idioma',
    'status.online': 'Sistema en Línea',
    'status.warning': 'Advertencia del Sistema',
    'status.critical': 'Sistema Crítico',
    'dashboard.title': 'Panel de Operaciones',
    'dashboard.subtitle': 'Vista general en tiempo real del rendimiento de la cadena de valor',
    'dashboard.kpi.oee': 'Efectividad General del Equipo',
    'dashboard.kpi.throughput': 'Rendimiento Diario',
    'dashboard.kpi.defectRate': 'Tasa de Defectos',
    'dashboard.kpi.energyEfficiency': 'Eficiencia Energética',
    'dashboard.kpi.sustainability': 'Puntuación de Sostenibilidad',
    'dashboard.kpi.supplyChainRisk': 'Índice de Riesgo de Cadena de Suministro',
    'dashboard.alerts': 'Alertas Recientes',
    'dashboard.viewAll': 'Ver Todas',
    'alerts.title': 'Centro de Alertas',
    'alerts.subtitle': 'Monitorear y gestionar alertas del sistema',
    'alerts.filter.all': 'Todas',
    'alerts.filter.critical': 'Críticas',
    'alerts.filter.warning': 'Advertencias',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Reconocer',
    'alerts.acknowledged': 'Reconocida',
    'alerts.details': 'Detalles',
    'alerts.sampleTitle': 'Alertas de ejemplo.',
    'alerts.sampleBody': 'Estas entradas se midieron a partir de los datos brutos de {company}: la tabla de origen, la columna y el valor medido aparecen debajo de cada alerta. Ilustran el flujo de alertas; no hay conexión en vivo.',
    'alerts.sampleBadge': 'Ejemplo',
    'common.apply': 'Aplicar',
    'common.dismiss': 'Descartar',
    'common.seeDetails': 'Ver Detalles',
    'common.export': 'Exportar',
    'common.loading': 'Cargando...',
    'common.error': 'Ocurrió un error. Por favor, inténtelo de nuevo.',
    'common.noData': 'No hay datos disponibles',
    'onboarding.welcome': 'Bienvenido a SMAP',
    'onboarding.step1.title': 'Vista General del Panel',
    'onboarding.step1.desc': 'Monitoree sus indicadores clave de rendimiento y el estado del sistema de un vistazo.',
    'onboarding.step2.title': 'Gemelos Digitales Cognitivos',
    'onboarding.step2.desc': 'Explore representaciones digitales en tiempo real y ejecute simulaciones hipotéticas.',
    'onboarding.step3.title': 'Soporte de Decisiones y Sostenibilidad',
    'onboarding.step3.desc': 'Obtenga recomendaciones de optimización con IA y evaluaciones de sostenibilidad.',
    'onboarding.step4.title': 'Centro de Alertas',
    'onboarding.step4.desc': 'Manténgase informado sobre eventos críticos y notificaciones del sistema.',
    'onboarding.next': 'Siguiente',
    'onboarding.prev': 'Anterior',
    'onboarding.finish': 'Comenzar',
    'onboarding.skip': 'Saltar Tour',
    'onboarding.dontShowAgain': 'No volver a mostrar',
    'adminTour.welcome': 'Bienvenido a SMAP Admin',
    'adminTour.step1.title': 'Usuarios y Roles',
    'adminTour.step1.desc': 'Cree, edite y elimine cuentas, y asigne el rol de gerente, ingeniero u operador. Solo ve y gestiona los usuarios de su propio caso de uso.',
    'adminTour.step2.title': 'Páginas y Tarjetas',
    'adminTour.step2.desc': 'Decida qué páginas y qué tarjetas puede ver cada rol. El cambio se aplica de inmediato en la vista de ese rol.',
    'adminTour.step3.title': 'Alcance y almacenamiento',
    'adminTour.step3.desc': 'Esta es una configuración de demostración y se guarda únicamente en este navegador. Cubre su propio caso de uso; el otro caso de uso se configura desde su propia cuenta de administrador.',
  },
  fr: {
    'nav.dashboard': 'Tableau de Bord',
    'nav.digitalTwin': 'Jumeaux Numériques Cognitifs',
    'nav.valueChain': 'Chaîne de Valeur',
    'nav.valueChainSim': 'Simulation de Chaîne de Valeur',
    'nav.manufacturing': 'Fabrication',
    'nav.manufacturingSim': 'Simulation de Fabrication',
    'nav.logistics': 'Logistique',
    'nav.product': 'Qualité Produit',
    'nav.sustainability': 'Évaluation de Durabilité',
    'nav.decisionSupport': 'Aide à la Décision',
    'nav.moDss': 'Optimisation Multi-Objectifs',
    'nav.knowledgeGraph': 'Graphe de Connaissances Décisionnelles',
    'nav.alertCenter': "Centre d'Alertes",
    'nav.glossary': 'Glossaire',
    'nav.helpTraining': 'Aide & Formation',
    'header.search': 'Rechercher...',
    'header.lastHours': 'Dernières 24 Heures',
    'header.last7Days': '7 Derniers Jours',
    'header.last30Days': '30 Derniers Jours',
    'header.last90Days': '90 Derniers Jours',
    'header.refresh': 'Actualiser les données',
    'header.notifications': 'Notifications',
    'header.language': 'Langue',
    'status.online': 'Système en Ligne',
    'status.warning': 'Avertissement Système',
    'status.critical': 'Système Critique',
    'dashboard.title': 'Tableau de Bord Opérationnel',
    'dashboard.subtitle': 'Vue en temps réel de la performance de la chaîne de valeur',
    'dashboard.kpi.oee': 'Efficacité Globale des Équipements',
    'dashboard.kpi.throughput': 'Débit Quotidien',
    'dashboard.kpi.defectRate': 'Taux de Défauts',
    'dashboard.kpi.energyEfficiency': 'Efficacité Énergétique',
    'dashboard.kpi.sustainability': 'Score de Durabilité',
    'dashboard.kpi.supplyChainRisk': "Indice de Risque de la Chaîne d'Approvisionnement",
    'dashboard.alerts': 'Alertes Récentes',
    'dashboard.viewAll': 'Voir Tout',
    'alerts.title': "Centre d'Alertes",
    'alerts.subtitle': 'Surveiller et gérer les alertes système',
    'alerts.filter.all': 'Toutes',
    'alerts.filter.critical': 'Critiques',
    'alerts.filter.warning': 'Avertissements',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Acquitter',
    'alerts.acknowledged': 'Acquittée',
    'alerts.details': 'Détails',
    'alerts.sampleTitle': 'Alertes d’exemple.',
    'alerts.sampleBody': 'Ces entrées sont mesurées à partir des données brutes de {company} — la table source, la colonne et la valeur mesurée figurent sous chaque alerte. Elles illustrent le flux d’alertes ; il n’y a aucune connexion en direct.',
    'alerts.sampleBadge': 'Exemple',
    'common.apply': 'Appliquer',
    'common.dismiss': 'Rejeter',
    'common.seeDetails': 'Voir Détails',
    'common.export': 'Exporter',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue. Veuillez réessayer.',
    'common.noData': 'Aucune donnée disponible',
    'onboarding.welcome': 'Bienvenue sur SMAP',
    'onboarding.step1.title': 'Aperçu du Tableau de Bord',
    'onboarding.step1.desc': "Surveillez vos indicateurs clés de performance et l'état du système en un coup d'œil.",
    'onboarding.step2.title': 'Jumeaux Numériques Cognitifs',
    'onboarding.step2.desc': 'Explorez les représentations numériques en temps réel et lancez des simulations.',
    'onboarding.step3.title': 'Aide à la Décision & Durabilité',
    'onboarding.step3.desc': "Obtenez des recommandations d'optimisation par l'IA et des évaluations de durabilité.",
    'onboarding.step4.title': "Centre d'Alertes",
    'onboarding.step4.desc': 'Restez informé des événements critiques et des notifications système.',
    'onboarding.next': 'Suivant',
    'onboarding.prev': 'Précédent',
    'onboarding.finish': 'Commencer',
    'onboarding.skip': 'Passer le Tour',
    'onboarding.dontShowAgain': 'Ne plus afficher',
    'adminTour.welcome': 'Bienvenue sur SMAP Admin',
    'adminTour.step1.title': 'Utilisateurs et Rôles',
    'adminTour.step1.desc': "Créez, modifiez et supprimez des comptes, et attribuez le rôle de responsable, d'ingénieur ou d'opérateur. Vous ne voyez et ne gérez que les utilisateurs de votre propre cas d'usage.",
    'adminTour.step2.title': 'Pages et Cartes',
    'adminTour.step2.desc': "Déterminez quelles pages et quelles cartes chaque rôle peut voir. Une modification s'applique immédiatement à la vue de ce rôle.",
    'adminTour.step3.title': 'Périmètre et stockage',
    'adminTour.step3.desc': "Il s'agit d'une configuration de démonstration, enregistrée uniquement dans ce navigateur. Elle couvre votre propre cas d'usage ; l'autre cas d'usage se configure depuis son propre compte administrateur.",
  },
  zh: {
    'nav.dashboard': '仪表板',
    'nav.digitalTwin': '认知数字孪生',
    'nav.valueChain': '价值链',
    'nav.valueChainSim': '价值链仿真',
    'nav.manufacturing': '制造',
    'nav.manufacturingSim': '制造仿真',
    'nav.logistics': '物流',
    'nav.product': '产品质量',
    'nav.sustainability': '可持续性评估',
    'nav.decisionSupport': '决策支持',
    'nav.moDss': '多目标优化',
    'nav.knowledgeGraph': '决策知识图谱',
    'nav.alertCenter': '警报中心',
    'nav.glossary': '术语表',
    'nav.helpTraining': '帮助与培训',
    'header.search': '搜索...',
    'header.lastHours': '过去24小时',
    'header.last7Days': '过去7天',
    'header.last30Days': '过去30天',
    'header.last90Days': '过去90天',
    'header.refresh': '刷新数据',
    'header.notifications': '通知',
    'header.language': '语言',
    'status.online': '系统在线',
    'status.warning': '系统警告',
    'status.critical': '系统危急',
    'dashboard.title': '运营仪表板',
    'dashboard.subtitle': '价值链绩效实时概览',
    'dashboard.kpi.oee': '整体设备效率',
    'dashboard.kpi.throughput': '日吞吐量',
    'dashboard.kpi.defectRate': '缺陷率',
    'dashboard.kpi.energyEfficiency': '能源效率',
    'dashboard.kpi.sustainability': '可持续性评分',
    'dashboard.kpi.supplyChainRisk': '供应链风险指数',
    'dashboard.alerts': '最近警报',
    'dashboard.viewAll': '查看全部',
    'alerts.title': '警报中心',
    'alerts.subtitle': '监控和管理系统警报',
    'alerts.filter.all': '全部',
    'alerts.filter.critical': '危急',
    'alerts.filter.warning': '警告',
    'alerts.filter.info': '信息',
    'alerts.acknowledge': '确认',
    'alerts.acknowledged': '已确认',
    'alerts.details': '详情',
    'alerts.sampleTitle': '示例警报。',
    'alerts.sampleBody': '这些条目由 {company} 的原始数据测量得出——来源表、字段和实测值显示在每条警报下方。它们用于演示警报流程；没有实时连接。',
    'alerts.sampleBadge': '示例',
    'common.apply': '应用',
    'common.dismiss': '忽略',
    'common.seeDetails': '查看详情',
    'common.export': '导出',
    'common.loading': '加载中...',
    'common.error': '发生错误。请重试。',
    'common.noData': '暂无数据',
    'onboarding.welcome': '欢迎使用 SMAP',
    'onboarding.step1.title': '仪表板概览',
    'onboarding.step1.desc': '一目了然地监控您的关键绩效指标和系统健康状态。',
    'onboarding.step2.title': '认知数字孪生',
    'onboarding.step2.desc': '探索实时数字表示并运行假设分析仿真。',
    'onboarding.step3.title': '决策支持与可持续性',
    'onboarding.step3.desc': '获取AI驱动的优化建议和可持续性评估。',
    'onboarding.step4.title': '警报中心',
    'onboarding.step4.desc': '随时了解关键事件和系统通知。',
    'onboarding.next': '下一步',
    'onboarding.prev': '上一步',
    'onboarding.finish': '开始使用',
    'onboarding.skip': '跳过导览',
    'onboarding.dontShowAgain': '不再显示',
    'adminTour.welcome': '欢迎使用 SMAP 管理后台',
    'adminTour.step1.title': '用户与角色',
    'adminTour.step1.desc': '创建、编辑和删除账户，并分配经理、工程师或操作员角色。您只能查看和管理本用例的用户。',
    'adminTour.step2.title': '页面与卡片',
    'adminTour.step2.desc': '决定每个角色可以看到哪些页面和哪些卡片。更改会立即在该角色的视图中生效。',
    'adminTour.step3.title': '范围与存储',
    'adminTour.step3.desc': '这是演示配置，仅保存在本浏览器中。它仅涵盖您自己的用例；另一个用例由其自己的管理员账户配置。',
  },
  tr: {
    'nav.dashboard': 'Kontrol Paneli',
    'nav.digitalTwin': 'Bilişsel Dijital İkizler',
    'nav.valueChain': 'Değer Zinciri',
    'nav.valueChainSim': 'Değer Zinciri Simülasyonu',
    'nav.manufacturing': 'Üretim Hattı',
    'nav.manufacturingSim': 'Üretim Simülasyonu',
    'nav.logistics': 'Lojistik',
    'nav.product': 'Ürün Kalitesi',
    'nav.sustainability': 'Sürdürülebilirlik Değerlendirmesi',
    'nav.decisionSupport': 'Karar Destek',
    'nav.moDss': 'Çok Amaçlı Optimizasyon',
    'nav.knowledgeGraph': 'Karar Bilgi Grafı',
    'nav.alertCenter': 'Uyarı Merkezi',
    'nav.glossary': 'Terimler Sözlüğü',
    'nav.helpTraining': 'Yardım ve Eğitim',
    'header.search': 'Ara...',
    'header.lastHours': 'Son 24 Saat',
    'header.last7Days': 'Son 7 Gün',
    'header.last30Days': 'Son 30 Gün',
    'header.last90Days': 'Son 90 Gün',
    'header.refresh': 'Verileri yenile',
    'header.notifications': 'Bildirimler',
    'header.language': 'Dil',
    'status.online': 'Sistem Çevrimiçi',
    'status.warning': 'Sistem Uyarısı',
    'status.critical': 'Sistem Kritik',
    'dashboard.title': 'Operasyon Paneli',
    'dashboard.subtitle': 'Değer zinciri performansının gerçek zamanlı görünümü',
    'dashboard.kpi.oee': 'Toplam Ekipman Verimliliği',
    'dashboard.kpi.throughput': 'Günlük Üretim',
    'dashboard.kpi.defectRate': 'Hata Oranı',
    'dashboard.kpi.energyEfficiency': 'Enerji Verimliliği',
    'dashboard.kpi.sustainability': 'Sürdürülebilirlik Puanı',
    'dashboard.kpi.supplyChainRisk': 'Tedarik Zinciri Risk Endeksi',
    'dashboard.alerts': 'Son Uyarılar',
    'dashboard.viewAll': 'Tümünü Gör',
    'alerts.title': 'Uyarı Merkezi',
    'alerts.subtitle': 'Sistem uyarılarını izle ve yönet',
    'alerts.filter.all': 'Tümü',
    'alerts.filter.critical': 'Kritik',
    'alerts.filter.warning': 'Uyarı',
    'alerts.filter.info': 'Bilgi',
    'alerts.acknowledge': 'Onayla',
    'alerts.acknowledged': 'Onaylandı',
    'alerts.details': 'Detaylar',
    'alerts.sampleTitle': 'Örnek alarmlar.',
    'alerts.sampleBody': 'Bu kayıtlar {company} ham verisinden ölçülmüştür — kaynak tablo, kolon ve ölçülen değer her alarmın altında yazılıdır. Alarm akışını göstermek içindir; canlı bağlantı yoktur.',
    'alerts.sampleBadge': 'Örnek',
    'common.apply': 'Uygula',
    'common.dismiss': 'Yoksay',
    'common.seeDetails': 'Detayları Gör',
    'common.export': 'Dışa Aktar',
    'common.loading': 'Yükleniyor...',
    'common.error': 'Bir hata oluştu. Lütfen tekrar deneyin.',
    'common.noData': 'Veri bulunamadı',
    'onboarding.welcome': "SMAP'e Hoş Geldiniz",
    'onboarding.step1.title': 'Panele Genel Bakış',
    'onboarding.step1.desc': 'Temel performans göstergelerinizi ve sistem durumunu bir bakışta izleyin.',
    'onboarding.step2.title': 'Bilişsel Dijital İkizler',
    'onboarding.step2.desc': 'Gerçek zamanlı dijital temsilleri keşfedin ve senaryo (what-if) simülasyonları çalıştırın.',
    'onboarding.step3.title': 'Karar Destek ve Sürdürülebilirlik',
    'onboarding.step3.desc': 'Yapay zekâ destekli optimizasyon önerileri ve sürdürülebilirlik değerlendirmeleri alın.',
    'onboarding.step4.title': 'Uyarı Merkezi',
    'onboarding.step4.desc': 'Kritik olaylar ve sistem bildirimleri hakkında bilgi sahibi olun.',
    'onboarding.next': 'İleri',
    'onboarding.prev': 'Geri',
    'onboarding.finish': 'Başla',
    'onboarding.skip': 'Turu Atla',
    'onboarding.dontShowAgain': 'Bir daha gösterme',
    'adminTour.welcome': "SMAP Admin'e Hoş Geldiniz",
    'adminTour.step1.title': 'Kullanıcılar ve Roller',
    'adminTour.step1.desc': 'Hesap oluşturun, düzenleyin ve silin; yönetici, mühendis veya operatör rolünü atayın. Yalnızca kendi kullanım senaryonuzun kullanıcılarını görür ve yönetirsiniz.',
    'adminTour.step2.title': 'Sayfalar ve Kartlar',
    'adminTour.step2.desc': 'Hangi sayfayı ve hangi kartı hangi rolün göreceğine buradan karar verirsiniz. Değişiklik, o rolün görünümüne anında yansır.',
    'adminTour.step3.title': 'Kapsam ve saklama',
    'adminTour.step3.desc': 'Bu bir demo yapılandırmasıdır ve yalnızca bu tarayıcıda saklanır. Kendi kullanım senaryonuzu kapsar; diğer senaryo kendi yönetici hesabından yapılandırılır.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('smap-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('smap-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
