import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'de' | 'es' | 'fr' | 'zh' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.digitalTwin': 'Operations',
    'nav.valueChain': 'Value Chain',
    'nav.valueChainSim': 'Value Chain Simulation',
    'nav.manufacturing': 'Manufacturing',
    'nav.manufacturingSim': 'Manufacturing Simulation',
    'nav.logistics': 'Logistics',
    'nav.product': 'Product Quality',
    'nav.sustainability': 'Sustainability Assessment',
    'nav.decisionSupport': 'Decision Support',
    'nav.moDss': 'Multi-Objective Optimization',
    'nav.scheduling': 'Production Scheduling',
    'nav.alertCenter': 'Alert Center',
    'nav.glossary': 'Glossary',
    'nav.helpTraining': 'Help & Training',
    'header.search': 'Search...',
    'header.lastHours': 'Last 24 Hours',
    'header.last7Days': 'Last 7 Days',
    'header.last30Days': 'Last 30 Days',
    'header.last90Days': 'Last 90 Days',
    'header.refresh': 'Refresh data',
    'header.notifications': 'Notifications',
    'header.language': 'Language',
    'status.online': 'System Online',
    'status.warning': 'System Warning',
    'status.critical': 'System Critical',
    'dashboard.title': 'Operations Dashboard',
    'dashboard.subtitle': 'Real-time overview of value chain performance',
    'dashboard.kpi.oee': 'Overall Equipment Effectiveness',
    'dashboard.kpi.throughput': 'Daily Throughput',
    'dashboard.kpi.defectRate': 'Defect Rate',
    'dashboard.kpi.energyEfficiency': 'Energy Efficiency',
    'dashboard.kpi.sustainability': 'Sustainability Score',
    'dashboard.kpi.supplyChainRisk': 'Supply Chain Risk Index',
    'dashboard.alerts': 'Recent Alerts',
    'dashboard.viewAll': 'View All',
    'alerts.title': 'Alert Center',
    'alerts.subtitle': 'Monitor and manage system alerts',
    'alerts.filter.all': 'All',
    'alerts.filter.critical': 'Critical',
    'alerts.filter.warning': 'Warning',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Acknowledge',
    'alerts.acknowledged': 'Acknowledged',
    'alerts.details': 'Details',
    'common.apply': 'Apply',
    'common.dismiss': 'Dismiss',
    'common.seeDetails': 'See Details',
    'common.export': 'Export',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred. Please try again.',
    'common.noData': 'No data available',
    'onboarding.welcome': 'Welcome to SMAP',
    'onboarding.step1.title': 'Dashboard Overview',
    'onboarding.step1.desc': 'Monitor your key performance indicators and system health at a glance.',
    'onboarding.step2.title': 'Cognitive Digital Twins',
    'onboarding.step2.desc': 'Explore real-time digital representations and run what-if simulations.',
    'onboarding.step3.title': 'Decision Support & Sustainability',
    'onboarding.step3.desc': 'Get AI-powered optimization recommendations and sustainability assessments.',
    'onboarding.step4.title': 'Alert Center',
    'onboarding.step4.desc': 'Stay informed about critical events and system notifications.',
    'onboarding.next': 'Next',
    'onboarding.prev': 'Previous',
    'onboarding.finish': 'Get Started',
    'onboarding.skip': 'Skip Tour',
  },
  de: {
    'nav.dashboard': 'Dashboard',
    'nav.digitalTwin': 'Kognitive Digitale Zwillinge',
    'nav.valueChain': 'Wertschöpfungskette',
    'nav.valueChainSim': 'Wertschöpfungsketten-Simulation',
    'nav.manufacturing': 'Fertigung',
    'nav.manufacturingSim': 'Fertigungs-Simulation',
    'nav.logistics': 'Logistik',
    'nav.product': 'Produktqualität',
    'nav.sustainability': 'Nachhaltigkeitsbewertung',
    'nav.decisionSupport': 'Entscheidungsunterstützung',
    'nav.moDss': 'Mehrziel-Optimierung',
    'nav.scheduling': 'Produktionsplanung',
    'nav.alertCenter': 'Warnzentrale',
    'nav.glossary': 'Glossar',
    'nav.helpTraining': 'Hilfe & Schulung',
    'header.search': 'Suchen...',
    'header.lastHours': 'Letzte 24 Stunden',
    'header.last7Days': 'Letzte 7 Tage',
    'header.last30Days': 'Letzte 30 Tage',
    'header.last90Days': 'Letzte 90 Tage',
    'header.refresh': 'Daten aktualisieren',
    'header.notifications': 'Benachrichtigungen',
    'header.language': 'Sprache',
    'status.online': 'System Online',
    'status.warning': 'Systemwarnung',
    'status.critical': 'System Kritisch',
    'dashboard.title': 'Betriebs-Dashboard',
    'dashboard.subtitle': 'Echtzeit-Übersicht der Wertschöpfungskettenleistung',
    'dashboard.kpi.oee': 'Gesamtanlageneffektivität',
    'dashboard.kpi.throughput': 'Täglicher Durchsatz',
    'dashboard.kpi.defectRate': 'Fehlerquote',
    'dashboard.kpi.energyEfficiency': 'Energieeffizienz',
    'dashboard.kpi.sustainability': 'Nachhaltigkeitsbewertung',
    'dashboard.kpi.supplyChainRisk': 'Lieferkettenrisikoindex',
    'dashboard.alerts': 'Aktuelle Warnungen',
    'dashboard.viewAll': 'Alle anzeigen',
    'alerts.title': 'Warnzentrale',
    'alerts.subtitle': 'Systemwarnungen überwachen und verwalten',
    'alerts.filter.all': 'Alle',
    'alerts.filter.critical': 'Kritisch',
    'alerts.filter.warning': 'Warnung',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Bestätigen',
    'alerts.acknowledged': 'Bestätigt',
    'alerts.details': 'Details',
    'common.apply': 'Anwenden',
    'common.dismiss': 'Verwerfen',
    'common.seeDetails': 'Details anzeigen',
    'common.export': 'Exportieren',
    'common.loading': 'Laden...',
    'common.error': 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    'common.noData': 'Keine Daten verfügbar',
    'onboarding.welcome': 'Willkommen bei SMAP',
    'onboarding.step1.title': 'Dashboard-Übersicht',
    'onboarding.step1.desc': 'Überwachen Sie Ihre wichtigsten Leistungskennzahlen und den Systemzustand auf einen Blick.',
    'onboarding.step2.title': 'Kognitive Digitale Zwillinge',
    'onboarding.step2.desc': 'Erkunden Sie Echtzeit-Darstellungen und führen Sie Was-wäre-wenn-Simulationen durch.',
    'onboarding.step3.title': 'Entscheidungsunterstützung & Nachhaltigkeit',
    'onboarding.step3.desc': 'Erhalten Sie KI-gestützte Optimierungsempfehlungen und Nachhaltigkeitsbewertungen.',
    'onboarding.step4.title': 'Warnzentrale',
    'onboarding.step4.desc': 'Bleiben Sie über kritische Ereignisse und Systembenachrichtigungen informiert.',
    'onboarding.next': 'Weiter',
    'onboarding.prev': 'Zurück',
    'onboarding.finish': 'Loslegen',
    'onboarding.skip': 'Tour überspringen',
  },
  es: {
    'nav.dashboard': 'Panel de Control',
    'nav.digitalTwin': 'Gemelos Digitales Cognitivos',
    'nav.valueChain': 'Cadena de Valor',
    'nav.valueChainSim': 'Simulación de Cadena de Valor',
    'nav.manufacturing': 'Fabricación',
    'nav.manufacturingSim': 'Simulación de Fabricación',
    'nav.logistics': 'Logística',
    'nav.product': 'Calidad del Producto',
    'nav.sustainability': 'Evaluación de Sostenibilidad',
    'nav.decisionSupport': 'Soporte de Decisiones',
    'nav.moDss': 'Optimización Multiobjetivo',
    'nav.scheduling': 'Programación de Producción',
    'nav.alertCenter': 'Centro de Alertas',
    'nav.glossary': 'Glosario',
    'nav.helpTraining': 'Ayuda y Formación',
    'header.search': 'Buscar...',
    'header.lastHours': 'Últimas 24 Horas',
    'header.last7Days': 'Últimos 7 Días',
    'header.last30Days': 'Últimos 30 Días',
    'header.last90Days': 'Últimos 90 Días',
    'header.refresh': 'Actualizar datos',
    'header.notifications': 'Notificaciones',
    'header.language': 'Idioma',
    'status.online': 'Sistema en Línea',
    'status.warning': 'Advertencia del Sistema',
    'status.critical': 'Sistema Crítico',
    'dashboard.title': 'Panel de Operaciones',
    'dashboard.subtitle': 'Vista general en tiempo real del rendimiento de la cadena de valor',
    'dashboard.kpi.oee': 'Efectividad General del Equipo',
    'dashboard.kpi.throughput': 'Rendimiento Diario',
    'dashboard.kpi.defectRate': 'Tasa de Defectos',
    'dashboard.kpi.energyEfficiency': 'Eficiencia Energética',
    'dashboard.kpi.sustainability': 'Puntuación de Sostenibilidad',
    'dashboard.kpi.supplyChainRisk': 'Índice de Riesgo de Cadena de Suministro',
    'dashboard.alerts': 'Alertas Recientes',
    'dashboard.viewAll': 'Ver Todas',
    'alerts.title': 'Centro de Alertas',
    'alerts.subtitle': 'Monitorear y gestionar alertas del sistema',
    'alerts.filter.all': 'Todas',
    'alerts.filter.critical': 'Críticas',
    'alerts.filter.warning': 'Advertencias',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Reconocer',
    'alerts.acknowledged': 'Reconocida',
    'alerts.details': 'Detalles',
    'common.apply': 'Aplicar',
    'common.dismiss': 'Descartar',
    'common.seeDetails': 'Ver Detalles',
    'common.export': 'Exportar',
    'common.loading': 'Cargando...',
    'common.error': 'Ocurrió un error. Por favor, inténtelo de nuevo.',
    'common.noData': 'No hay datos disponibles',
    'onboarding.welcome': 'Bienvenido a SMAP',
    'onboarding.step1.title': 'Vista General del Panel',
    'onboarding.step1.desc': 'Monitoree sus indicadores clave de rendimiento y el estado del sistema de un vistazo.',
    'onboarding.step2.title': 'Gemelos Digitales Cognitivos',
    'onboarding.step2.desc': 'Explore representaciones digitales en tiempo real y ejecute simulaciones hipotéticas.',
    'onboarding.step3.title': 'Soporte de Decisiones y Sostenibilidad',
    'onboarding.step3.desc': 'Obtenga recomendaciones de optimización con IA y evaluaciones de sostenibilidad.',
    'onboarding.step4.title': 'Centro de Alertas',
    'onboarding.step4.desc': 'Manténgase informado sobre eventos críticos y notificaciones del sistema.',
    'onboarding.next': 'Siguiente',
    'onboarding.prev': 'Anterior',
    'onboarding.finish': 'Comenzar',
    'onboarding.skip': 'Saltar Tour',
  },
  fr: {
    'nav.dashboard': 'Tableau de Bord',
    'nav.digitalTwin': 'Jumeaux Numériques Cognitifs',
    'nav.valueChain': 'Chaîne de Valeur',
    'nav.valueChainSim': 'Simulation de Chaîne de Valeur',
    'nav.manufacturing': 'Fabrication',
    'nav.manufacturingSim': 'Simulation de Fabrication',
    'nav.logistics': 'Logistique',
    'nav.product': 'Qualité Produit',
    'nav.sustainability': 'Évaluation de Durabilité',
    'nav.decisionSupport': 'Aide à la Décision',
    'nav.moDss': 'Optimisation Multi-Objectifs',
    'nav.scheduling': 'Planification de Production',
    'nav.alertCenter': "Centre d'Alertes",
    'nav.glossary': 'Glossaire',
    'nav.helpTraining': 'Aide & Formation',
    'header.search': 'Rechercher...',
    'header.lastHours': 'Dernières 24 Heures',
    'header.last7Days': '7 Derniers Jours',
    'header.last30Days': '30 Derniers Jours',
    'header.last90Days': '90 Derniers Jours',
    'header.refresh': 'Actualiser les données',
    'header.notifications': 'Notifications',
    'header.language': 'Langue',
    'status.online': 'Système en Ligne',
    'status.warning': 'Avertissement Système',
    'status.critical': 'Système Critique',
    'dashboard.title': 'Tableau de Bord Opérationnel',
    'dashboard.subtitle': 'Vue en temps réel de la performance de la chaîne de valeur',
    'dashboard.kpi.oee': 'Efficacité Globale des Équipements',
    'dashboard.kpi.throughput': 'Débit Quotidien',
    'dashboard.kpi.defectRate': 'Taux de Défauts',
    'dashboard.kpi.energyEfficiency': 'Efficacité Énergétique',
    'dashboard.kpi.sustainability': 'Score de Durabilité',
    'dashboard.kpi.supplyChainRisk': "Indice de Risque de la Chaîne d'Approvisionnement",
    'dashboard.alerts': 'Alertes Récentes',
    'dashboard.viewAll': 'Voir Tout',
    'alerts.title': "Centre d'Alertes",
    'alerts.subtitle': 'Surveiller et gérer les alertes système',
    'alerts.filter.all': 'Toutes',
    'alerts.filter.critical': 'Critiques',
    'alerts.filter.warning': 'Avertissements',
    'alerts.filter.info': 'Info',
    'alerts.acknowledge': 'Acquitter',
    'alerts.acknowledged': 'Acquittée',
    'alerts.details': 'Détails',
    'common.apply': 'Appliquer',
    'common.dismiss': 'Rejeter',
    'common.seeDetails': 'Voir Détails',
    'common.export': 'Exporter',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue. Veuillez réessayer.',
    'common.noData': 'Aucune donnée disponible',
    'onboarding.welcome': 'Bienvenue sur SMAP',
    'onboarding.step1.title': 'Aperçu du Tableau de Bord',
    'onboarding.step1.desc': "Surveillez vos indicateurs clés de performance et l'état du système en un coup d'œil.",
    'onboarding.step2.title': 'Jumeaux Numériques Cognitifs',
    'onboarding.step2.desc': 'Explorez les représentations numériques en temps réel et lancez des simulations.',
    'onboarding.step3.title': 'Aide à la Décision & Durabilité',
    'onboarding.step3.desc': "Obtenez des recommandations d'optimisation par l'IA et des évaluations de durabilité.",
    'onboarding.step4.title': "Centre d'Alertes",
    'onboarding.step4.desc': 'Restez informé des événements critiques et des notifications système.',
    'onboarding.next': 'Suivant',
    'onboarding.prev': 'Précédent',
    'onboarding.finish': 'Commencer',
    'onboarding.skip': 'Passer le Tour',
  },
  zh: {
    'nav.dashboard': '仪表板',
    'nav.digitalTwin': '认知数字孪生',
    'nav.valueChain': '价值链',
    'nav.valueChainSim': '价值链仿真',
    'nav.manufacturing': '制造',
    'nav.manufacturingSim': '制造仿真',
    'nav.logistics': '物流',
    'nav.product': '产品质量',
    'nav.sustainability': '可持续性评估',
    'nav.decisionSupport': '决策支持',
    'nav.moDss': '多目标优化',
    'nav.scheduling': '生产调度',
    'nav.alertCenter': '警报中心',
    'nav.glossary': '术语表',
    'nav.helpTraining': '帮助与培训',
    'header.search': '搜索...',
    'header.lastHours': '过去24小时',
    'header.last7Days': '过去7天',
    'header.last30Days': '过去30天',
    'header.last90Days': '过去90天',
    'header.refresh': '刷新数据',
    'header.notifications': '通知',
    'header.language': '语言',
    'status.online': '系统在线',
    'status.warning': '系统警告',
    'status.critical': '系统危急',
    'dashboard.title': '运营仪表板',
    'dashboard.subtitle': '价值链绩效实时概览',
    'dashboard.kpi.oee': '整体设备效率',
    'dashboard.kpi.throughput': '日吞吐量',
    'dashboard.kpi.defectRate': '缺陷率',
    'dashboard.kpi.energyEfficiency': '能源效率',
    'dashboard.kpi.sustainability': '可持续性评分',
    'dashboard.kpi.supplyChainRisk': '供应链风险指数',
    'dashboard.alerts': '最近警报',
    'dashboard.viewAll': '查看全部',
    'alerts.title': '警报中心',
    'alerts.subtitle': '监控和管理系统警报',
    'alerts.filter.all': '全部',
    'alerts.filter.critical': '危急',
    'alerts.filter.warning': '警告',
    'alerts.filter.info': '信息',
    'alerts.acknowledge': '确认',
    'alerts.acknowledged': '已确认',
    'alerts.details': '详情',
    'common.apply': '应用',
    'common.dismiss': '忽略',
    'common.seeDetails': '查看详情',
    'common.export': '导出',
    'common.loading': '加载中...',
    'common.error': '发生错误。请重试。',
    'common.noData': '暂无数据',
    'onboarding.welcome': '欢迎使用 SMAP',
    'onboarding.step1.title': '仪表板概览',
    'onboarding.step1.desc': '一目了然地监控您的关键绩效指标和系统健康状态。',
    'onboarding.step2.title': '认知数字孪生',
    'onboarding.step2.desc': '探索实时数字表示并运行假设分析仿真。',
    'onboarding.step3.title': '决策支持与可持续性',
    'onboarding.step3.desc': '获取AI驱动的优化建议和可持续性评估。',
    'onboarding.step4.title': '警报中心',
    'onboarding.step4.desc': '随时了解关键事件和系统通知。',
    'onboarding.next': '下一步',
    'onboarding.prev': '上一步',
    'onboarding.finish': '开始使用',
    'onboarding.skip': '跳过导览',
  },
  tr: {
    'nav.dashboard': 'Kontrol Paneli',
    'nav.digitalTwin': 'Bilissel Dijital Ikizler',
    'nav.valueChain': 'Deger Zinciri',
    'nav.valueChainSim': 'Deger Zinciri Simulasyonu',
    'nav.manufacturing': 'Uretim Hatti',
    'nav.manufacturingSim': 'Uretim Simulasyonu',
    'nav.logistics': 'Lojistik',
    'nav.product': 'Urun Kalitesi',
    'nav.sustainability': 'Surdurulebilirlik Degerlendirmesi',
    'nav.decisionSupport': 'Karar Destek',
    'nav.moDss': 'Cok Amacli Optimizasyon',
    'nav.scheduling': 'Uretim Cizelgeleme',
    'nav.alertCenter': 'Uyari Merkezi',
    'nav.glossary': 'Terimler Sozlugu',
    'nav.helpTraining': 'Yardim ve Egitim',
    'header.search': 'Ara...',
    'header.lastHours': 'Son 24 Saat',
    'header.last7Days': 'Son 7 Gun',
    'header.last30Days': 'Son 30 Gun',
    'header.last90Days': 'Son 90 Gun',
    'header.refresh': 'Verileri yenile',
    'header.notifications': 'Bildirimler',
    'header.language': 'Dil',
    'status.online': 'Sistem Cevrimici',
    'status.warning': 'Sistem Uyarisi',
    'status.critical': 'Sistem Kritik',
    'dashboard.title': 'Operasyon Paneli',
    'dashboard.subtitle': 'Deger zinciri performansinin gercek zamanli gorunumu',
    'dashboard.kpi.oee': 'Toplam Ekipman Verimliligi',
    'dashboard.kpi.throughput': 'Gunluk Uretim',
    'dashboard.kpi.defectRate': 'Hata Orani',
    'dashboard.kpi.energyEfficiency': 'Enerji Verimliligi',
    'dashboard.kpi.sustainability': 'Surdurulebilirlik Puani',
    'dashboard.kpi.supplyChainRisk': 'Tedarik Zinciri Risk Endeksi',
    'dashboard.alerts': 'Son Uyarilar',
    'dashboard.viewAll': 'Tumunu Gor',
    'alerts.title': 'Uyari Merkezi',
    'alerts.subtitle': 'Sistem uyarilarini izle ve yonet',
    'alerts.filter.all': 'Tumu',
    'alerts.filter.critical': 'Kritik',
    'alerts.filter.warning': 'Uyari',
    'alerts.filter.info': 'Bilgi',
    'alerts.acknowledge': 'Onayla',
    'alerts.acknowledged': 'Onaylandi',
    'alerts.details': 'Detaylar',
    'common.apply': 'Uygula',
    'common.dismiss': 'Reddet',
    'common.seeDetails': 'Detaylari Gor',
    'common.export': 'Disari Aktar',
    'common.loading': 'Yukleniyor...',
    'common.error': 'Bir hata olustu. Lutfen tekrar deneyin.',
    'common.noData': 'Veri bulunamadi',
    'onboarding.welcome': "SMAP'e Hos Geldiniz",
    'onboarding.step1.title': 'Panel Genel Bakis',
    'onboarding.step1.desc': 'Temel performans gostergelerinizi ve sistem durumunu bir bakista izleyin.',
    'onboarding.step2.title': 'Bilissel Dijital Ikizler',
    'onboarding.step2.desc': 'Gercek zamanli dijital temsilleri kesfedin ve ne-olursa simulasyonlari calistirin.',
    'onboarding.step3.title': 'Karar Destek ve Surdurulebilirlik',
    'onboarding.step3.desc': 'Yapay zeka destekli optimizasyon onerileri ve surdurulebilirlik degerlendirmeleri alin.',
    'onboarding.step4.title': 'Uyari Merkezi',
    'onboarding.step4.desc': 'Kritik olaylar ve sistem bildirimleri hakkinda bilgi sahibi olun.',
    'onboarding.next': 'Ileri',
    'onboarding.prev': 'Geri',
    'onboarding.finish': 'Basla',
    'onboarding.skip': 'Turu Atla',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('smap-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('smap-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
